# Basic dependabot.yml file with
# minimum configuration

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
#    reviewers:
#      - "dstoianov"
