= Url Shortener project based on spring boot icon:power-off[]
ifdef::env-github[]
:imagesdir:
 https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons: font
:toc: left
:toclevels: 4
:toc-title: Table of Contents

[TIP]
It's possible to use emojis as admonition icons on GitHub.

== 1. Requirements

. Git
. Java JDK 11
. Apache Maven

== 2. Spring Boot Tutorials icon:fire[]

. API documentation for the project located here `http://localhost:8080/doc`

== 3. Docker Image

. Package `jar` file `mvn clean package`
. Build image `docker build . --tag url-shortener` or `docker build --no-cache -t url-shortener .`
. Build image `docker build . --tag url-shortener:1.0` with version (image tag)
. Run docker image `docker run -it -p 8080:8080 url-shortener:latest`
. Run with Spring profile `docker run -e "SPRING_PROFILES_ACTIVE=prod" -p 8085:8085 -t url-shortener`

docker run -rm -e "SPRING_PROFILES_ACTIVE=dev" -p 8080:8080 -t url-shortener

. run jar local `java -Dspring.profiles.active=prod -jar target/url-shortener-1.0.0-SNAPSHOT.jar`

```sh
FROM adoptopenjdk/openjdk11:alpine-slim as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM adoptopenjdk/openjdk11:alpine-jre
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","-Dspring.profiles.active=prod","se.techinsight.Application"]
```

===  Actuator service

* https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html[Official documentation]
* https://spring.io/guides/gs/actuator-service/[actuator-service]
** link to actuator http://localhost:8080/actuator

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

=== Data base changing

. liquibase
. flyway

===  Springdoc OpenAPI

* https://springdoc.github.io/springdoc-openapi-demos/

```property
# swagger-ui custom path
springdoc.swagger-ui.path=/doc
```

open in browser `http://localhost:8080/doc` for documentation

== Test icon:info-circle[]

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
* Every list item has at least one paragraph of content, which may be wrapped, even using a hanging indent.
+
Additional paragraphs or blocks are adjoined by putting a list continuation on a line adjacent to both blocks.
+
list continuation:: a plus sign (`{plus}`) on a line by itself

* A literal paragraph does not require a list continuation.

 $ gem install asciidoctor

* AsciiDoc lists may contain any complex content.
+
[cols="2",options="header"]
|===
|Application
|Language

|AsciiDoc
|Python

|Asciidoctor
|Ruby
|===

=== Code Structure

. https://github.com/n2o/url-shortener[good UI View using spring boot]
. https://github.com/khandelwal-arpit/springboot-starterkit[very nice example Web MVC App]
. https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-structuring-your-code[Default Spring boot recomendation]
. https://www.tutorialspoint.com/spring_boot/spring_boot_code_structure.htm
. https://www.javaguides.net/2019/01/standard-project-structure-for-spring-boot-projects.html[several approaches]
. https://www.javadevjournal.com/spring-boot/creating-a-web-application-with-spring-boot/
. https://www.techiedelight.com/display-custom-error-pages-in-spring-boot/[Error page handle in WEB]
. https://attacomsian.com/blog[Spring Boot and Thymeleaf]

=== Docker

. https://dzone.com/articles/microservices-and-devops-1
. https://medium.com/swlh/dockerizing-spring-boot-application-df5ae7dd1e37


http://kaviddiss.com/2015/07/18/building-modern-web-applications-using-java-spring/
https://hackernoon.com/url-shortening-service-in-java-spring-boot-and-redis-d2a0f8848a1d


* https://fontawesome.com/icons?d=gallery&m=free[list of free icons]
* icon:heartbeat[]
* icon:power-off[]
* icon:motorcycle[]
* icon:street-view[]
* icon:ship[]
* icon:bus[]
* icon:eur[]
* icon:cab[]
* icon:calculator[]
* icon:anchor[]