# Enable graceful shutdown
server.shutdown: graceful

logging:
  level:
    .: ERROR
    org.springframework: ERROR
    se.techinsight: INFO
#    org.apache.http.wire: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#    org.springframework.web.client.TestRestTemplate: DEBUG


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /doc
  packages-to-scan: se.techinsight.urlshortener


spring:
  application:
    name: @project.name@
  profiles:
    active: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # turn off automatic schema creation to avoid conflicts
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  #    serialization:
  #      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

# Configuring info endpoint, /actuator/info
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
  # environment variables
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

---

spring:
  profiles: dev

  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/

server:
  port: 8080

host:
  url: http://localhost:${server.port}

---

spring:
  profiles: prod
  h2.console.enabled: false

server:
  port: 8085

host:
  url: "https://daria.tk"

