name: Java-CI

on: [push]

jobs:

  ci_part:
    name: Compile and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repo
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: compile
        run: mvn -B compile
      - name: run unit tests
        run: mvn -B verify -Dspring.profiles.active=test
      - uses: actions/upload-artifact@v2
        with:
          name: maven target
          path: target/

  sonar_part:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    needs: [ci_part]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: target/
      - name: display target dir
        run: |
          ls -la
          tree
      #      - name: Set up JDK 11
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: 11.0.4
      - name: SonarCloud Scan
        run: |
          ls -la
          mvn -B sonar:sonar -Dsonar.organization=dstoianov -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
